// Auth
export const AUTH_CHECK_TOKEN = 'AUTH_CHECK_TOKEN';
export const AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_FORGOT_PASSWORD_REQUEST';
export const AUTH_FORGOT_PASSWORD_RESET = 'AUTH_FORGOT_PASSWORD_RESET';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_EMAIL_REQUEST = 'CHANGE_EMAIL_REQUEST';
export const GET_USER_AUTH_BY_ID = 'GET_USER_AUTH_BY_ID';

// Loading
export const ENABLE_LOADING = 'ENABLE_LOADING';
