export const LAYOUT = {
    TOGGLE_SIDEBAR_DESKTOP: 'TOGGLE_SIDEBAR_DESKTOP',
    TOGGLE_SIDEBAR_MOBILE: 'TOGGLE_SIDEBAR_MOBILE',
    SET_SIDEBAR: 'SET_SIDEBAR',
    SET_LOADING: 'SET_LOADING'
};

export const AUTH = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    FETCH_AUTH: 'FETCH_AUTH',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_FORGOT_PASSWORD_REQUEST: 'AUTH_FORGOT_PASSWORD_REQUEST',
    AUTH_FORGOT_PASSWORD_RESET: 'AUTH_FORGOT_PASSWORD_RESET'
};

// User management
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS';
export const FETCH_USER_UPDATE_SUCCESS = 'FETCH_USER_UPDATE_SUCCESS';

export const SET_LOCALE = 'SET_LOCALE';
